# Default language if you have a multi-language setup
DefaultContentLanguage = "en"

baseURL = ""
theme = "amperage"
pygmentsUseClasses = true

# Number of posts shown per page
 paginate = 1 

# Language sections
[languages]
    [languages.en]
        contentDir = "content"
        languageName = "English"
        languageCode = "en"
        title = "Jasmin Schaedler"
        description = "Jasmin Schaedler Portfolio Website"
        weight = 1
    [languages.de]
        contentDir = "content/de"
        languageName = "Deutsch"
        languageCode = "de"
        title = "Jasmin Schaedler"
        description = "Jasmin Schaedler Portfolio Website"
        weight = 2

# Menu elements


    [[languages.en.menu.main]]
    identifier = "home"
    name = "HOME"
    url = "/"
    weight = 1

    [[languages.en.menu.main]]
    identifier = "about"
    name = "ABOUT"
    url = "/about"
    weight = 2

    [[languages.en.menu.main]]
    identifier = "upcoming"
    name = "UPCOMING"
    url = "/upcoming"
    weight = 3

    [[languages.en.menu.main]]
    identifier = "projects"
    name = "PROJECTS"
    url = "/projects"
    weight = 4

    [[languages.en.menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv"
    weight = 5

    [[languages.en.menu.main]]
    identifier = "imprint"
    name = "IMPRINT"
    url = "/imprint"
    weight = 6


# Enable only tags taxonomy
[taxonomies]
    tag = "tags"

[params]
    copyright = "Jasmin Schädler / Amperage" # Name shown on footer copyright
    themeColor = "#333" # Theme color displayed on mobile browsers

    # Default AMP components for the whole site
    ampElements = ["amp-analytics", "amp-social-share", "amp-install-serviceworker", "amp-iframe"]

    # Google Analytics code
    googleAnalytics = "UA-128498798-1"

    # Adsense publisher code
    adsensePublisher = "ca-pub-123456789"

    # Social sites for metatags
    facebookSite = "sabinajasmin"
    instagramSite = "fraumitlandschaft"

    # Structured data elements
    socialProfiles = ["https://www.facebook.com/sabinajasmin","https://www.instagram.com/fraumitlandschaft/"]

    publisherName = "amperage"
    publisherLogo = "/logo.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60

[markup]
    defaultMarkdownHandler = "blackfriday"

